### ISSUE TITLE
Personal ideas for the Arc Menu

### ISSUE THREAD

**Issue by lexruee** [lexruee/Arc-Menu#1]
Some personal ideas for the Arc Menu: https://github.com/LinxGem33/Arc-Menu
Some are inspired by the issue: https://github.com/LinxGem33/Arc-Menu/issues/1

Features:
* ~~About Page~~
* ~~Trash shortcut~~
* ~~Gui option to change menu icon~~
* Gui option to enable/disable a Terminal shortcut
* Gui option to enable/disable a System Monitor shortcut
* ~~Gui Option to set the menu on left or right~~
* ~~Gui option to enable/disable the default top left hot corner~~
* ~~Gui option to bind the Super Key to the Arc Menu~~
  * ~~Gui option to bind a custom keybinding to the Arc Menu~~
* Resizable menu
* ~~Suspend Button~~
* Add hints/tool tips to the menu buttons (power, lock, logout, suspend)
  * Gui option to enable/disable tool tips
* Favourite app launcher
* Recently used applications
* Search
  * support for entering words
  * implement a basic vector space model?
  * file searching functionality with gnome tracker?
  * calculator built in search
* ~~make install / uninstall / bundle (Makefile)~~

Project:
* Project Website based on Github pages

**Comment by LinxGem33** [comment]
@lexruee 

hi Ive added a prefs.js ,tooltips.js and a widgets.js with the APIs needed to make your development maybe a little bit easier its just a base for some of the features you want to implement check it out and let me know what you think.

kind regards

**Comment by lexruee** [comment]
@LinxGem33 
Hi, thanks for the skeleton code :-). In the recent days, I was distracted from my Arc Menu work by the latest Debian Stretch release :smiley:.

So far I implemented an empty settings panel using a GTK.Notebook Widget. Nothing special so far.
As soon as I have implemented one or two features, I'll make a pull-request. 
![arc-menu-prefs](https://user-images.githubusercontent.com/649340/27295484-6621fd38-551d-11e7-9dc2-2fc8e449f62a.png)

**Comment by LinxGem33** [comment]
@lexruee 

fantastic, ill keep an eye out for your pull request in the meantime ill see how i can integrate new features once we get the settings up and running I’m going to try contact one user who specialises in translations and see if he/she can contribute to the project by way of integrating the translations already set up in the local folder , ill keep you informed of the progress also here is some code to maybe help you with disabling the hot corner ill also try and form some code for other things too.

```javascript
        let panelSettings = new Gtk.Box({
            orientation: Gtk.Orientation.VERTICAL,
            margin_bottom: 10
        });

        let panelSettingsTitle = new Gtk.Label({
            label: _("<b>Panel Settings</b>"),
            use_markup: true,
            xalign: 0,
            margin_top: 5,
            margin_bottom: 5
        });


        let disableHotCornerBox = new Gtk.Box({
            spacing: 20,
            orientation: Gtk.Orientation.HORIZONTAL,
            homogeneous: false,
            margin_left: 20,
            margin_top: 5,
            margin_bottom: 5,
            margin_right: 10
        });
        let disableHotCornerLabel = new Gtk.Label({
            label: _("Disable activities hot corner"),
            use_markup: true,
            xalign: 0,
            hexpand: true
        });
        let disableHotCornerSwitch = new Gtk.Switch ({
            halign: Gtk.Align.END
        });
        disableHotCornerSwitch.set_active(this.settings.get_boolean('disable-activities-hotcorner'));
        disableHotCornerSwitch.connect("notify::active", Lang.bind(this, function(check) {
            this.settings.set_boolean('disable-activities-hotcorner', check.get_active());
        }));

        disableHotCornerBox.add(disableHotCornerLabel);
        disableHotCornerBox.add(disableHotCornerSwitch);
```

**Comment by LinxGem33** [comment]
@lexruee 
##
schema code for the position
##
```xml
<?xml version="1.0" encoding="UTF-8"?>
<schemalist gettext-domain="gnome-shell-extensions-arc-menu">
  <enum id='org.gnome.shell.extensions.arc-menu.visible'>
    <value value="0" nick="left"/>
    <value value="1" nick="center"/>
    <value value="2" nick="right"/>
  </enum>
    </key>
    <key name="position-in-panel" enum="org.gnome.shell.extensions.arc-menu.position">
      <default>'right'</default>
      <summary>Position in Panel</summary>
    </key>
  </schema>
</schemalist>
```
##
prefs.js code to set the position of a Arc menu on the panel either ,left,right or centre 
##
```javascript
let presentLabel = '<b>' + _("Display Options") + '</b>';
        this.add(new Gtk.Label({
            label: presentLabel, use_markup: true,
            halign: Gtk.Align.START
    }));

    vbox.add(checkContainer);

    let positionContainer = new Gtk.HBox({spacing: 5});
    let positionLabel = new Gtk.Label({label: _('Arc Menu Position on the Panel')});
    let positionSelector = new Gtk.ComboBoxText();

    positionContainer.pack_start(positionLabel, 0,0,0);
    positionContainer.pack_end(positionSelector, 0,0,0);

    ['left','center','right'].forEach(function(item) {
      positionSelector.append_text(item);
    });

    positionSelector.set_active(this._settings.get_enum(SETTINGS_POSITION));

    let self = this;

    positionSelector.connect('changed', function(pos) {
      self._settings.set_enum(SETTINGS_POSITION, positionSelector.get_active());
    });
```
##
main menu code for the position
```javascript
const SETTINGS_POSITION = 'position-in-panel';

  resetPanelPos: function() {

    Main.panel.statusArea['Arc menu'] = null;
    Main.panel.addToStatusArea('Arc menu', this, 1, this._menuPosition);

  },

  setPrefs: function() {
 
   this._prevMenuPosition = this._menuPosition;

    this._menuPosition = this._settings.get_string(SETTINGS_POSITION);
  },
```
##
kind regards
