### ISSUE TITLE
Menu hotkey event should trigger on key release, not on key press

### ISSUE THREAD

**Issue by mjohnson8165** [lexruee/Arc-Menu#3]
I do realize that the current behavior may have been intended as it is (makes it all seem more responsive), but unfortunately it causes problems for other Gnome keyboard shortcuts (namely, everything using and starting with the Super key). For instance, **Super** + **Right Arrow** would normally tile the focused window to the right side of the its current screen, but the **Super** key triggers the extension's menu right then upon pressing it, which in turn kills the combo.

Not sure if having it react upon the key release would do the trick and I couldn't test that theory, hence no pull request, hence the lone issue here, humbly addressed to greater people who may know a thing or two about extensions :)

**Comment by lexruee** [comment]
@mjohnson8165 
Hi! The official Arc-Menu repo can be found here:
https://gitlab.com/LinxGem33/Arc-Menu
